/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
          "summitblue": "#4C6FFF",
          "summitlight": "#EDF1FF",
          "summitdarkblue": "#0054a6",
          "summit-mainbgblue": "#DFE6FB",
          "summit-mainbg":"#FAFAFA",
          "summit-highlightblue": "#EDF1FF",
          "summit-light-blue-border": "#CDD7FF",
          "summit-maintext": "#858585",
          "summit-text-light-gray":"#979797",
          "summit-bordergray": "#d9d9d9",
          "summit-border-lightgray": "#e4e4e4",
          "summit-border-mid-gray":"#cacaca",
          "summit-disabled-gray":"#c7c7c7",
          "summit-button-gray": "#7a7a7a",
          "summit-aside-bar-blue": "#2256dd",
          "summit-table-light-blue":"#E9EBF5",
          "summit-table-darker-blue":"#CFD5E9"
        },
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji"
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji"
      ],
    },
    fontWeight: {
      thin: "100",
      hairline: "100",
      extralight: "200",
      light: "300",
      normal: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
      extrabold: "800",
      black: "900"
    },
  },
  plugins: [],
};

